#
# Copyright (c) 2026, Daily
#
# SPDX-License-Identifier: BSD-2-Clause
#

"""Unit tests for the build driver's policy and completeness checks.

Everything here runs without cmake, a compiler, or ffmpeg: the checks are pure
functions over cmake's *outputs* (the enabled-module set, the link-command
text), so we test them by seeding fakes — including the failure modes we never
want to see on a real machine.
"""

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))

from build_native import (
    DEFAULT_MODULES,
    BuildPolicyError,
    check_completeness,
    check_gpl_link_lines,
    check_gpl_modules,
    find_gpl_link_tokens,
    parse_modules_detected,
    parse_modules_from_static_c,
)

CLEAN_MODULES = set(DEFAULT_MODULES)


# --- parsers -----------------------------------------------------------------


def test_parse_static_c_extracts_module_exports():
    text = (
        "/* static.c - autogenerated by cmake */\n"
        "extern const struct mod_export exports_g711;\n"
        "extern const struct mod_export exports_opus;\n"
        "const struct mod_export *mod_table[] = { &exports_g711, &exports_opus, NULL };\n"
    )
    assert parse_modules_from_static_c(text) == {"g711", "opus"}


def test_parse_modules_detected_from_configure_output():
    out = "-- Some line\nMODULES_DETECTED=g711;opus;srtp\n-- Configuring done\n"
    assert parse_modules_detected(out) == {"g711", "opus", "srtp"}


# --- GPL module check (seeded fakes) ------------------------------------------


def test_unrequested_avcodec_fails_the_build():
    with pytest.raises(BuildPolicyError):
        check_gpl_modules(CLEAN_MODULES | {"avcodec"}, allowed_extra=set())


def test_requested_avcodec_passes_with_notice(capsys):
    check_gpl_modules(CLEAN_MODULES | {"avcodec"}, allowed_extra={"avcodec"})
    err = capsys.readouterr().err
    assert "NOTICE" in err and "GPL" in err  # informational, never blocking


def test_clean_module_set_passes_silently(capsys):
    check_gpl_modules(CLEAN_MODULES, allowed_extra=set())
    assert "NOTICE" not in capsys.readouterr().err


# --- GPL link-line check (seeded fakes) ----------------------------------------


def test_gpl_link_token_detection():
    assert find_gpl_link_tokens("cc -o baresip foo.o -lavcodec -lm")
    assert find_gpl_link_tokens("link /opt/homebrew/lib/libx264.dylib bar.o")
    assert not find_gpl_link_tokens("cc -o baresip foo.o -lssl -lcrypto -lopus")


def test_unrequested_gpl_link_line_fails():
    with pytest.raises(BuildPolicyError):
        check_gpl_link_lines({"link.txt": "cc -o x a.o -lavcodec"}, allowed_extra=set())


def test_requested_gpl_link_line_passes():
    check_gpl_link_lines({"link.txt": "cc -o x a.o -lavcodec"}, allowed_extra={"avcodec"})


def test_presence_of_ffmpeg_on_machine_is_not_friction(tmp_path):
    """Regression test for the false-positive class this design exists to avoid.

    A machine may have ffmpeg installed, and a reused build directory may even
    carry stale cache text mentioning it. The checks consult only the enabled-
    module set and the link commands — so a clean decision surface must pass
    regardless of what exists on disk around it.
    """
    cache = tmp_path / "CMakeCache.txt"
    cache.write_text(
        "FFMPEG_LIBRARIES:FILEPATH=/opt/homebrew/lib/libavcodec.dylib\n"
        "FFMPEG_INCLUDE_DIRS:PATH=/opt/homebrew/include\n"
    )
    # Clean decisions, dirty surroundings: must pass.
    check_gpl_modules(CLEAN_MODULES, allowed_extra=set())
    check_gpl_link_lines({"link.txt": "cc -o baresip foo.o -lssl -lopus"}, allowed_extra=set())
    assert cache.exists()  # the point: its contents were never consulted


# --- completeness guard ---------------------------------------------------------


def test_completeness_exact_match_passes():
    check_completeness(CLEAN_MODULES, CLEAN_MODULES)


def test_missing_module_fails_loudly():
    with pytest.raises(BuildPolicyError, match="did not build"):
        check_completeness(CLEAN_MODULES - {"opus"}, CLEAN_MODULES)


def test_surplus_module_fails_loudly():
    with pytest.raises(BuildPolicyError, match="not requested"):
        check_completeness(CLEAN_MODULES | {"gst"}, CLEAN_MODULES)
